version: '3.1'

services:
    db:
        image: mariadb:10.6
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            TZ: Europe/Berlin
            TIME_ZONE: Europe/Berlin
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin
        restart: always
        depends_on:
            -   db
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
